---
title: "Palmerpenguins"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    
---

```{r setup, include=FALSE}
#library(flexdashboard)
library(ggplot2)
library(tidyverse)
library(palmerpenguins)
library(paletteer)
library(reactable)
library(cranlogs)
library(tibble)
# Install thematic and un-comment for themed static plots (i.e., ggplot2)
# thematic::thematic_rmd()
ggplot2::theme_set(theme_bw())
```

# CRAN downloads

```{r eval=FALSE}
# set eval to true for first if cran_logs.csv doesn't exist
dl<- cranlogs::cran_downloads(packages = c("palmerpenguins","distill","blogdown"),from = "2020-08-01",to="2021-12-01") 

write.csv(dl,"cran_logs.csv")
```

```{r}
dl<- read.csv("cran_logs.csv")
```


Column {data-width=450 .tabset}
-----------------------------------------------------------------------

### Daily downloads

```{r}

dl$date<- as.Date(dl$date,format="%Y-%m-%d")
ggplot(dl, aes(date, count,color=fct_reorder2(package,date,count))) +
  geom_line()+
  labs(y="Daily downloads", color="package",x=NULL) +
  theme_bw()

```

### Daily downloads (smoother)

```{r}
thematic::thematic_rmd()
# from https://github.com/hadley/cran-downloads/blob/master/server.R
show_trend <- function(df) {
  count_ts <- ts(df$count, frequency = 7)
  stl <- tryCatch(
    as.data.frame(stl(count_ts, "periodic")$time.series),
    error = function(e) data.frame(trend = df$count, remainder = 0)
  )
  df$trend <- stl$trend
  df$remainder <- stl$remainder
  df
}
trend <- dl %>% group_by(package) %>% do(show_trend(.))

ggplot(trend, aes(date, colour = fct_reorder2(package, date, count))) +
  geom_linerange(aes(ymin = trend, ymax = trend + remainder), colour = "grey85", alpha = .5, lwd = 1) +
  geom_line(aes(y = trend), lwd = 1) +
  labs(y = "Daily downloads (smoothed)", color = "package", x = NULL) +
  scale_color_paletteer_d("nationalparkcolors::Arches")
```


### Cumulative downloads

```{r}
cumulative_dl <- 
  dl %>% 
  group_by(package) %>% 
  mutate(cum_dl = cumsum(count)) %>% 
  ungroup() 

ggplot(cumulative_dl, 
       aes(date, 
           cum_dl, 
           color = fct_reorder2(package, date, cum_dl)
           )
       ) +
  geom_line(lwd = 1) +
  labs(y = "Cumulative downloads (past year)", color = "package", x = NULL) +
  scale_y_continuous(expand = c(0, 0)) +
  scale_x_date() +
  scale_color_paletteer_d("nationalparkcolors::Arches")
```


Column {data-width=550}
-----------------------------------------------------------------------

### Median weekly downloads

```{r}
weekly_median <-
  dl %>% 
  group_by(week = lubridate::week(date), package) %>% 
  summarize(median_dl = median(count),
            begin_week = min(date))
ggplot(weekly_median, aes(begin_week, median_dl, 
               color = fct_reorder2(package, begin_week, median_dl))) +
  geom_line(lwd = 1) +
  labs(y = "Median weekly downloads", color = "package", x = NULL) +
  scale_color_paletteer_d("nationalparkcolors::Arches")
```

### Median downloads data
```{r}
reactable(weekly_median)
```



# Penguin plots

## Column

### Species by island

```{r}
ggplot(penguins, aes(x = island, fill = species)) +
  geom_bar(alpha = 0.8) +
  scale_fill_paletteer_d("nationalparkcolors::Arches",
                    guide = "none") +
  facet_wrap(~species, ncol = 1) +
  coord_flip()
```

### Sex by species

```{r}
ggplot(penguins, aes(x = flipper_length_mm,
                     y = body_mass_g)) +
  geom_point(aes(color = sex)) +
  scale_color_paletteer_d("nationalparkcolors::Arches",
                     na.translate = FALSE) +
  facet_wrap(~species)
```

## Column

### If you ignore species...

```{r}
bill_no_species <- ggplot(data = penguins,
                         aes(x = bill_length_mm,
                             y = bill_depth_mm)) +
  geom_point() +
  labs(title = "Penguin bill dimensions (omit species)",
       subtitle = "Palmer Station LTER",
       x = "Bill length (mm)",
       y = "Bill depth (mm)") +
  theme(plot.title.position = "plot",
        plot.caption = element_text(hjust = 0, face= "italic"),
        plot.caption.position = "plot") +
  geom_smooth(method = "lm", se = FALSE, color = "gray50")

bill_no_species
```

### If you include species...

```{r}
bill_len_dep <- ggplot(data = penguins,
                         aes(x = bill_length_mm,
                             y = bill_depth_mm,
                             group = species)) +
  geom_point(aes(color = species,
                 shape = species),
             size = 3,
             alpha = 0.8) +
  geom_smooth(method = "lm", se = FALSE, aes(color = species)) +
  theme_minimal() +
  scale_color_paletteer_d("nationalparkcolors::Arches") +
  labs(title = "Penguin bill dimensions",
       subtitle = "Bill length and depth for Adelie, Chinstrap and Gentoo Penguins at Palmer Station LTER",
       x = "Bill length (mm)",
       y = "Bill depth (mm)",
       color = "Penguin species",
       shape = "Penguin species") +
  theme(legend.position = c(0.85, 0.15),
        legend.background = element_rect(fill = "white", color = NA),
        plot.title.position = "plot",
        plot.caption = element_text(hjust = 0, face= "italic"),
        plot.caption.position = "plot")

bill_len_dep
```